

version: '3.0'
services:
  # Chatbot
  rasa:
    restart: always
    image: florianformentini/personalassistant:master
    networks: ['rasa-network']
    ports:
      - 5005:5005
    env_file: .env
    command: >
      bash -c "
      pip install -r requirements-bot.txt --no-cache &&
      python3 -m rasa run
      --enable-api
      --cors='*'
      --endpoints endpoints.yml
      --jwt-secret ${JWT_SECRET}
      --auth-token ${AUTH_TOKEN}
      "

  action-server:
    restart: always
    image: florianformentini/personalassistant-actionserver:latest
    networks: ['rasa-network']
    ports:
      - 5055:5055
    env_file: .env

networks: {rasa-network: {}}