# The config recipe
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# Configuration for Rasa NLU
# https://rasa.com/docs/rasa/nlu/components/
language: fr

# https://rasa.com/docs/rasa/tuning-your-model
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    entity_recognition: false    # faster when no entity used
    constrain_similarities: true
  # - name: EntitySynonymMapper
  # - name: ResponseSelector
  #   epochs: 100
  - name: FallbackClassifier
    threshold: 0.7
    # nlu_fallback if diff between first and second prediction < ambiguity_threshold
    ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  # lvl1 - next action prediction and entity recognition
  - name: TEDPolicy  
    max_history: 5
    epochs: 100
  # lvl2 - Stories
  # - name: MemoizationPolicy  
  # lvl6 - Rules
  - name: RulePolicy  
    core_fallback_threshold: 0.95
    core_fallback_action_name: action_default_fallback
    enable_fallback_prediction: true
    check_for_contradictions: true
    restrict_rules: true  # 1 rule = 1 user turn
